package mv.com.bml.mibapi.models.payments;

import java.io.Serializable;
import java.util.ArrayList;
import mv.com.bml.mibapi.models.misc.ValidationResult;

public class TransferActivity implements Serializable {
    public String accountDescDr;
    public String accountNameCr;
    public String accountNameDr;
    public String accountNoCr;
    public String accountNoDr;
    public String accountOptionDr;
    public String action;
    public String activityId;
    public String amount;
    public String bankClientCode;
    public String bankClientId;
    public String bankCodeDr;
    public BeneficiaryInfo beneficiaryAdhoc;
    public String beneficiaryId;
    public String beneficiaryType;
    public String branch;
    public String ccyAccountCr;
    public String ccyAccountDr;
    public String channelRefNo;
    public String chargesIncurredBy;
    public String crTranType;
    public String crudOperation;
    public ArrayList<String> dataObjectKeyMethods;
    public String drAvailableBalAmt;
    public String effectDt;
    public String equivAmt;
    public String eventCode;
    public String hash;
    public Boolean isBulkTransaction;
    public Boolean isFutureDatedTxn;
    public Boolean isRecurringTxn;
    public String message;
    public String otherDt;
    public String paymentDetails;
    public String recurFrequency;
    public String recurNoOfTimes;
    public String remarks;
    public String responseCode;
    public String spendCategoryDesc;
    public String spendCategoryId;
    public String spendSubCategoryDesc;
    public String spendSubCategoryId;
    public String status;
    public String tranAmt;
    public String tranCcy;
    public String tranDt;
    public String tranRefNo;
    public String tranStatus;
    public String tranType;
    public String userName;
    public ArrayList<ValidationResult> validationResultList;
}
